// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kazpdkmftoymgtoadqrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthenBka21mdG95bWd0b2FkcXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzEwODQsImV4cCI6MjA3MDIwNzA4NH0.itBpf8DpNzeH4JaCQ1glsIHCxO8_oiuKMZbFWk9hV8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});